### ISSUE TITLE
Bad navigation links in /api and /components page

### ISSUE THREAD

**Issue by mlenormand** [rstoenescu/quasar-site#10]
When we browse to the /api page or the /components page, the navigation link goes to the last subpage ("Other helper classes" for the /api page, "Video embedding" for the /components page). It should go to the first part of the first subpage of the page ("App visibility" for the /api page and "Action sheet" for the /components page)

![image](https://cloud.githubusercontent.com/assets/2403897/18162833/5c847ca8-7038-11e6-9d06-de236ed06761.png)

![image](https://cloud.githubusercontent.com/assets/2403897/18162895/98a6abde-7038-11e6-9c15-6ea4bd98022f.png)

**Comment by rstoenescu** [comment]
Ah, I see. Will fix it. Thanks!
