### ISSUE TITLE
Menu link matching "component"

### ISSUE THREAD

**Issue by vuchl** [rstoenescu/quasar-site#19]
When you visit the page "Components Sharing State" in the Guide, both tthe Menu link for guide and components is highlighted. Since the title includes the word "component". This set's the menu links css to `current`.
the responsible part of the code is here: https://github.com/rstoenescu/quasar-site/blob/67032a07cfbc0a3afb6df80ef42c535d50c6112e/themes/quasar/layout/partials/menu.ejs#L5

We could refactor the matches to  `page.path.match(/\/components\//)` and analog `page.path.match(/\/guide\//)` to include slashes.

More examples since tha matching is lazy:
- http://quasar-framework.org/guide/app-api-proxying-for-dev.html ("api")
- http://quasar-framework.org/components/search.html ("search")

**Comment by rstoenescu** [comment]
Thanks for pointing this out!
