### ISSUE TITLE
'Warning, Warning, Will Robinson!'

### ISSUE THREAD

**Issue by reneroth** [rstoenescu/quasar-site#508]
The code example for the [Notify component](https://github.com/quasarframework/quasar-framework.org/blob/b395942cb0aaa6e546b8912d42989019779baac9/source/components/notify.md#L19) currently misquotes Lost in Space. The correct quote is, of course, 'Danger, Will Robinson! Danger!'

This issue renders a great framework near unusable.

**Comment by rstoenescu** [comment]
Everyone stop using it until this is fixed! It's outrageous indeed. :))

Will get it fixed in next Quasar Play build.

**Comment by smolinari** [comment]
Hehehe....Ooops. I did that. :blush: 

Scott

**Comment by rstoenescu** [comment]
@smolinari Pssst, PR :)

**Comment by smolinari** [comment]
https://github.com/quasarframework/quasar-framework.org/pull/563 

Forgot to note this issue in the PR. Dammit!

Scott

**Comment by smolinari** [comment]
I'll fix the warnings in Play later. 

Scott
