### ISSUE TITLE
The dialog doc page still has a reference to the "Pick ranges" deprecated feature

### ISSUE THREAD

**Issue by mlenormand** [rstoenescu/quasar-site#7]
I believe "Pick ranges" has been deprecated/removed recently from Quasar. [The documentation page for dialogs
](http://quasar-framework.org/components/dialog.html) still has a reference to this feature : 

![image](https://cloud.githubusercontent.com/assets/2403897/18019030/6f9108aa-6bda-11e6-86b8-d83229fba378.png)

**Comment by rstoenescu** [comment]
Uh, oh, you're right. Please help me a little if you'll be so kind. There are two places on the doc website where you can make the appropriate changes in two clicks. Screenshots attached. It will create a pull request and I can accept it with one click only. I'm getting overloaded here by the issues :) Thank you so much for your help! You are awesome!!!

![screenshot from 2016-08-26 23 18 46](https://cloud.githubusercontent.com/assets/4665641/18019329/31318d5a-6be4-11e6-839a-13450aab060b.png)

![screenshot from 2016-08-26 23 18 53](https://cloud.githubusercontent.com/assets/4665641/18019328/312e0810-6be4-11e6-9d4f-5e7a77f0d2fc.png)

**Comment by mlenormand** [comment]
Pull request created and accepted for this issue. Can be closed ?

**Comment by rstoenescu** [comment]
Yep. It will go "live" when I also update the doc for v0.7
